### ISSUE TITLE
Persistent database across heroku pushes

### ISSUE THREAD

**Issue by drewrwilson** [codeforamerica/skillcamp#2]
The database gets nuked every time we push to heroku, need to figure out a way to keep it persistent so we can push changes without having to recreate data

**Comment by migurski** [comment]
Use Postgres.

**Comment by drewrwilson** [comment]
Cool, working on switching to postgres

**Comment by migurski** [comment]
Since you're already using SQLAlchemy, this should be a single variable configuration change: just the value of `DATABASE_URL` in my experience.

**Comment by migurski** [comment]
(And pushing a button on Heroku.com to magick up a DB of course)

**Comment by drewrwilson** [comment]
did it! 

:jeans: :necktie: :cactus:

**Comment by migurski** [comment]
Woo!

**Comment by drewrwilson** [comment]
Thanks for the advice!
